name: Enhancement
description: To suggest a new idea
title: "[EH] TITLE"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## IMPORTANT NOTICES BEFORE CREATING:
          - Only create if such an enhancement wasn't created in any form (siehe [Issues](https://github.com/FlexGamesGitHub/FlexBot/issues))
            - If one is similar, just add a comment
          - Also edit the title
  - type: input
    attributes:
      label: "Is a bug report related to this Enhancement?"
      description: "If yes please enter"
      placeholder: "#123"
      value: "No"
  - type: markdown
    attributes:
      value: "## THE ENHANCEMENT"
  - type: textarea
    attributes:
      label: "Description of your Idea"
      description: "A clear description of your imaginary"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Alternatives"
      description: "If there are alternatives, enter them here"  
  - type: markdown
    attributes:
      value: "## ADDITIONAL CONTEXT & CHECKOUT"
  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Everything else that is important to build your request into the bot"
  - type: checkboxes
    attributes: 
      label: Checkout
      options:
        - label: "I have changed the title"
          required: true
        - label: "I have filled out everything required"
          required: true
        - label: "I have checked for duplicates"
          required: true
  
