name: Issue Manager

on:
  schedule:
    - cron: "0 0 * * *"
  issue_comment:
    types:
      - created
      - edited
  issues:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled
  workflow_dispatch:

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            {
                "done": {
                    "delay": 0,
                    "message": "Thanks for creating! It was fixed or built in and will be closed"
                },
                "wontdo": {
                    "delay": 0,
                    "message": "Your issue won't be fixed or built in and will be closed"
                },
                "duplicate": {
                    "delay": 0,
                    "message": "You didn't check for duplicates! Closing this one"
                },
                "invalid": {
                    "delay": 0,
                    "message": "You didn't follow the Notices so your issue will be closed"
                },
                "question": {
                    "delay": 604800,
                    "message": "You didn't answer the question for too long so your issue will be closed"
                }
            }
